### ISSUE TITLE
请问 eleme 的前端都细分哪些职位呢？

### ISSUE THREAD

**Issue by think2011** [ElemeFE/node-practice#1]
我挺好奇 eleme 的前端有没有细分重构、交互、node服务端方向定位的，还是所有前端都需要会前端各个知识面呢？

**Comment by Lellansin** [comment]
Hi, 你好, 饿了么的大前端部门没有细分这些方向, 主要是按业务线来分组的.

**Comment by think2011** [comment]
恩，谢谢！
