### ISSUE TITLE
把宇宙第一外卖的node用于那些系统,用了那些库，踩过的坑，项目怎么划分，系统怎么划分的分享分享

### ISSUE THREAD

**Issue by uvd** [ElemeFE/node-practice#2]

**Comment by Lellansin** [comment]
今年有整理分享过一波饿厂踩的坑 （参见 http://2017.qconbeijing.com/presentation/737 ）不过由于<del>懒癌</del>工作比较忙文章没有写。。

**Comment by Lellansin** [comment]
feel free to reopen
